In [1]:
import os
os.listdir()

['.ipynb_checkpoints',
 'load_files.py',
 'supermarkets-commas.txt',
 'supermarkets-semi-colons.txt',
 'supermarkets.csv',
 'supermarkets.json',
 'supermarkets.xlsx',
 'Untitled.ipynb']

In [2]:
import pandas

In [4]:
df_csv = pandas.read_csv("supermarkets.csv")
df_csv.set_index("ID")

,Address,City,State,Country,Name,Employees
ID,,,,,,
1,3666 21st St,San Francisco,CA 94114,USA,Madeira,8
2,735 Dolores St,San Francisco,CA 94119,USA,Bready Shop,15
3,332 Hill St,San Francisco,California 94114,USA,Super River,25
4,3995 23rd St,San Francisco,CA 94114,USA,Ben's Shop,10
5,1056 Sanchez St,San Francisco,California,USA,Sanchez,12
6,551 Alvarado St,San Francisco,CA 94114,USA,Richvalley,20

In [5]:
print(df_csv)

   ID          Address           City             State Country         Name  \
0   1     3666 21st St  San Francisco          CA 94114     USA      Madeira
1   2   735 Dolores St  San Francisco          CA 94119     USA  Bready Shop
2   3      332 Hill St  San Francisco  California 94114     USA  Super River
3   4     3995 23rd St  San Francisco          CA 94114     USA   Ben's Shop
4   5  1056 Sanchez St  San Francisco        California     USA      Sanchez
5   6  551 Alvarado St  San Francisco          CA 94114     USA   Richvalley

   Employees
0          8
1         15
2         25
3         10
4         12
5         20

In [6]:
df_json = pandas.read_json("supermarkets.json")
df_json.set_index("ID")

,Address,City,Country,Employees,Name,State
ID,,,,,,
1,3666 21st St,San Francisco,USA,8,Madeira,CA 94114
2,735 Dolores St,San Francisco,USA,15,Bready Shop,CA 94119
3,332 Hill St,San Francisco,USA,25,Super River,California 94114
4,3995 23rd St,San Francisco,USA,10,Ben's Shop,CA 94114
5,1056 Sanchez St,San Francisco,USA,12,Sanchez,California
6,551 Alvarado St,San Francisco,USA,20,Richvalley,CA 94114

In [10]:
df_excel = pandas.read_excel("supermarkets.xlsx" , sheet_name = 0)
df_excel.set_index("ID")

,Address,City,State,Country,Supermarket Name,Number of Employees
ID,,,,,,
1,3666 21st St,San Francisco,CA 94114,USA,Madeira,8
2,735 Dolores St,San Francisco,CA 94119,USA,Bready Shop,15
3,332 Hill St,San Francisco,California 94114,USA,Super River,25
4,3995 23rd St,San Francisco,CA 94114,USA,Ben's Shop,10
5,1056 Sanchez St,San Francisco,California,USA,Sanchez,12
6,551 Alvarado St,San Francisco,CA 94114,USA,Richvalley,20

In [11]:
df_comma =  pandas.read_csv("supermarkets-commas.txt")
df_comma.set_index("ID")

,Address,City,State,Country,Name,Employees
ID,,,,,,
1,3666 21st St,San Francisco,CA 94114,USA,Madeira,8
2,735 Dolores St,San Francisco,CA 94119,USA,Bready Shop,15
3,332 Hill St,San Francisco,California 94114,USA,Super River,25
4,3995 23rd St,San Francisco,CA 94114,USA,Ben's Shop,10
5,1056 Sanchez St,San Francisco,California,USA,Sanchez,12
6,551 Alvarado St,San Francisco,CA 94114,USA,Richvalley,20

In [12]:
df_semicol =  pandas.read_csv("supermarkets-semi-colons.txt" , sep = ";")
df_semicol.set_index("ID")

,Address,City,State,Country,Name,Employees
ID,,,,,,
1,3666 21st St,San Francisco,CA 94114,USA,Madeira,8
2,735 Dolores St,San Francisco,CA 94119,USA,Bready Shop,15
3,332 Hill St,San Francisco,California 94114,USA,Super River,25
4,3995 23rd St,San Francisco,CA 94114,USA,Ben's Shop,10
5,1056 Sanchez St,San Francisco,California,USA,Sanchez,12
6,551 Alvarado St,San Francisco,CA 94114,USA,Richvalley,20

In [13]:
df_csv_internet = pandas.read_csv("https://pythonhow.com/supermarkets.csv")
df_csv_internet.set_index("ID")#Idon't have an internet connection now :(

URLError: <urlopen error [Errno 11001] getaddrinfo failed>