In [3]:
import pandas
from bokeh.plotting import figure, output_file, show
     
p=figure(plot_width=500,plot_height=400, tools='pan')
     
p.title.text="Cool Data"
p.title.text_color="Gray"
p.title.text_font="times"
p.title.text_font_style="bold"
p.xaxis.minor_tick_line_color=None
p.yaxis.minor_tick_line_color=None
p.xaxis.axis_label="Date"
p.yaxis.axis_label="Intensity"    

p.line([1,2,3],[4,5,6])
output_file("graph.html")
show(p)

In [10]:
df =pandas.read_excel("verlegenhuken.xlsx" , sheet_name = 0)
x = df["Temperature"] 
y = df["Pressure"]
df

       Year  Month  Day  Hour  Temperature  Pressure
0      2010     10    6     3          -30      9984
1      2010     10    6     9          -28      9992
2      2010     10    6    10          -24      9987
3      2010     10    6    11          -19      9987
4      2010     10    6    12          -19      9985
5      2010     10    6    13          -20      9982
6      2010     10    6    14          -15      9975
7      2010     10    6    15           -8      9971
8      2010     10    6    16           -5      9960
9      2010     10    6    17          -12      9953
10     2010     10    6    18          -13      9946
11     2010     10    6    19          -15      9937
12     2010     10    6    20           -7      9928
13     2010     10    6    21            1      9924
14     2010     10    6    22            5      9924
15     2010     10    6    23            5      9921
16     2010     10    7     0           11      9922
17     2010     10    7     1            5      9927
18     2010     10    7     2           10      9929
19     2010     10    7     3           10      9937
20     2010     10    7     4           16      9941
21     2010     10    7     5           13      9947
22     2010     10    7     6           16      9950
23     2010     10    7     7           27      9953
24     2010     10    7     8           16      9957
25     2010     10    7     9           16      9961
26     2010     10    7    10           18      9964
27     2010     10    7    11           23      9968
28     2010     10    7    12           23      9970
29     2010     10    7    13           39      9970
...     ...    ...  ...   ...          ...       ...
33072  2014     12   27     6         -181     10244
33073  2014     12   27     9         -188     10241
33074  2014     12   27    12         -175     10230
33075  2014     12   27    15         -184     10212
33076  2014     12   27    18         -174     10195
33077  2014     12   27    21         -147     10181
33078  2014     12   28     0         -160     10167
33079  2014     12   28     3         -143     10152
33080  2014     12   28     6         -138     10131
33081  2014     12   28     9         -137     10117
33082  2014     12   28    12         -127     10093
33083  2014     12   28    15         -126     10072
33084  2014     12   28    18         -119     10057
33085  2014     12   28    21         -131     10040
33086  2014     12   29     0         -134     10024
33087  2014     12   29     3         -135     10013
33088  2014     12   29     6         -126     10007
33089  2014     12   29     9         -131     10001
33090  2014     12   29    12         -109     10009
33091  2014     12   29    15         -101      9999
33092  2014     12   29    18          -94      9995
33093  2014     12   29    21          -88      9989
33094  2014     12   30     0         -101      9980
33095  2014     12   30     3          -96      9963
33096  2014     12   30     6         -104      9933
33097  2014     12   30     9         -116      9896
33098  2014     12   30    12         -103      9866
33099  2014     12   30    15          -97      9826
33100  2014     12   30    18          -93      9829
33101  2014     12   30    21          -86      9804

[33102 rows x 6 columns]

In [11]:
x = x/10
y = y /10

In [12]:
x , y

(0        -3.0
 1        -2.8
 2        -2.4
 3        -1.9
 4        -1.9
 5        -2.0
 6        -1.5
 7        -0.8
 8        -0.5
 9        -1.2
 10       -1.3
 11       -1.5
 12       -0.7
 13        0.1
 14        0.5
 15        0.5
 16        1.1
 17        0.5
 18        1.0
 19        1.0
 20        1.6
 21        1.3
 22        1.6
 23        2.7
 24        1.6
 25        1.6
 26        1.8
 27        2.3
 28        2.3
 29        3.9
          ...
 33072   -18.1
 33073   -18.8
 33074   -17.5
 33075   -18.4
 33076   -17.4
 33077   -14.7
 33078   -16.0
 33079   -14.3
 33080   -13.8
 33081   -13.7
 33082   -12.7
 33083   -12.6
 33084   -11.9
 33085   -13.1
 33086   -13.4
 33087   -13.5
 33088   -12.6
 33089   -13.1
 33090   -10.9
 33091   -10.1
 33092    -9.4
 33093    -8.8
 33094   -10.1
 33095    -9.6
 33096   -10.4
 33097   -11.6
 33098   -10.3
 33099    -9.7
 33100    -9.3
 33101    -8.6
 Name: Temperature, Length: 33102, dtype: float64, 0         998.4
 1         999.2
 2         998.7
 3         998.7
 4         998.5
 5         998.2
 6         997.5
 7         997.1
 8         996.0
 9         995.3
 10        994.6
 11        993.7
 12        992.8
 13        992.4
 14        992.4
 15        992.1
 16        992.2
 17        992.7
 18        992.9
 19        993.7
 20        994.1
 21        994.7
 22        995.0
 23        995.3
 24        995.7
 25        996.1
 26        996.4
 27        996.8
 28        997.0
 29        997.0
           ...
 33072    1024.4
 33073    1024.1
 33074    1023.0
 33075    1021.2
 33076    1019.5
 33077    1018.1
 33078    1016.7
 33079    1015.2
 33080    1013.1
 33081    1011.7
 33082    1009.3
 33083    1007.2
 33084    1005.7
 33085    1004.0
 33086    1002.4
 33087    1001.3
 33088    1000.7
 33089    1000.1
 33090    1000.9
 33091     999.9
 33092     999.5
 33093     998.9
 33094     998.0
 33095     996.3
 33096     993.3
 33097     989.6
 33098     986.6
 33099     982.6
 33100     982.9
 33101     980.4
 Name: Pressure, Length: 33102, dtype: float64)

In [17]:
p=figure(plot_width=500,plot_height=400 )

p.title.text="Temperature and Air Pressure"
p.title.text_color="Gray"
p.title.text_font="arial"
p.title.text_font_style="bold"
p.xaxis.minor_tick_line_color=None
p.yaxis.minor_tick_line_color=None
p.xaxis.axis_label="Temperature (°C)"
p.yaxis.axis_label="Pressure (hPa)"    

#p.circle(x , y , size= 6 , color="navy", alpha=0.5)
p.circle(x , y , size= 6 , alpha=0.5)
output_file("4_graph.html")
show(p)